[workspace]

members = [
    "skynet_macro",
    "migration",
    "skynet_api",
    "skynet",
    "plugin/monitor_api",
    "plugin/monitor",
    "plugin/agent_api",
    "plugin/agent",
    "plugin/task_api",
    "plugin/task",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
