[workspace]

members = [
    "actix-session",
    "skynet_macro",
    "skynet_i18n",
    "migration",
    "skynet",
    "plugin/monitor_service",
    "plugin/monitor",
    "plugin/agent_service",
    "plugin/agent",
    "plugin/task",
]
resolver = "2"
