version: "3"
services:
  skynet:
    image: imwxz/skynet:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data.db:/app/data.db
      - ./conf.yml:/app/conf.yml
      - ./data:/app/data
  redis:
    image: redis:latest
