version: "3"
services:
  skynet:
    image: imwxz/skynet:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data.db:/app/data.db
      - ./conf.yml:/app/conf.yml
  redis:
    image: redis:latest

networks:
  default:
    ipam:
      config:
        - subnet: 172.27.0.0/16
